// This file is generated by Sapper — do not edit it!
export const timestamp = 1534104560571;

export const assets = [
	"favicon.png",
	"GalaxieCopernicus-Book.woff",
	"global.css",
	"huge_agb_v5-webfont.woff",
	"logo-192.png",
	"logo-512.png",
	"manifest.json",
	"videos/console/openpanel.m4v"
];

export const shell = [
	"client/878c034218c19012e5f9/index.index.js",
	"client/878c034218c19012e5f9/main.js",
	"client/878c034218c19012e5f9/vendors~index.vendors~index.js",
	"client/index.9eb1cd56cb2369279997.hot-update.js",
	"client/9eb1cd56cb2369279997.hot-update.json"
];

export const routes = [
	{ pattern: /^\/?$/ }
];