// This file is generated by Sapper — do not edit it!
export const timestamp = 1532923581786;

export const assets = [
	"favicon.png",
	"GalaxieCopernicus-Book.woff",
	"global.css",
	"huge_agb_v5-webfont.woff",
	"logo-192.png",
	"logo-512.png",
	"manifest.json",
	"videos/open-devtools.m4v"
];

export const shell = [
	"client/65313e545dbad3dd6199/main.js",
	"client/65313e545dbad3dd6199/index.1.js",
	"client/65313e545dbad3dd6199/vendors~index.2.js"
];

export const routes = [
	{ pattern: /^\/?$/ }
];